/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class resizeImage_ResizeImage */

#ifndef _Included_resizeImage_ResizeImage
#define _Included_resizeImage_ResizeImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     resizeImage_ResizeImage
 * Method:    resizeImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_resizeImage_ResizeImage_resizeImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
